### ISSUE TITLE
Mod Issue URL is wrong

### ISSUE THREAD

**Issue by imvaskel** [BrassGoggledCoders/Podium#2]
The URL within mods.toml is incorrect, it should be `https://github.com/BrassGoggledCoders/Podium/issues` not `https://github.com/Brass-Goggled-Coders/Podium/issues`.

**Comment by SkySom** [comment]
https://github.com/BrassGoggledCoders/Podium/commit/80e30885c95913ebe2dc655cc9a7d1916724edf9 🧙‍♂️
